### ISSUE TITLE
Unparseable response

### ISSUE THREAD

**Issue by thyandrecardoso** [E-goi/sdk-java#4]
During a call to `.getAllContacts`, it seems the SDK is unable to handle some datetime strings in the response:

```
val res = apiInstance.getAllContacts(listId, offset, limit, null, null, null, null, null, null, null, null, null, null, null);
org.threeten.bp.format.DateTimeParseException: Text '0000-00-00 00:00:00' could not be parsed at index 10
  at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1588)
  at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
  at org.threeten.bp.OffsetDateTime.parse(OffsetDateTime.java:359)
  at org.egoi.client.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:327)
  at org.egoi.client.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:291)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  at com.google.gson.Gson.fromJson(Gson.java:927)
  at com.google.gson.Gson.fromJson(Gson.java:892)
  at com.google.gson.Gson.fromJson(Gson.java:841)
  at org.egoi.client.JSON.deserialize(JSON.java:247)
  at org.egoi.client.ApiClient.deserialize(ApiClient.java:765)
  at org.egoi.client.ApiClient.handleResponse(ApiClient.java:968)
  at org.egoi.client.ApiClient.execute(ApiClient.java:895)
  at org.egoi.client.api.ContactsApi.getAllContactsWithHttpInfo(ContactsApi.java:2027)
  at org.egoi.client.api.ContactsApi.getAllContacts(ContactsApi.java:1987)
  ... 36 elided
```

Indeed, in a `curl` call to that endpoint, one can see that the API replies with that `0000-00-00 00:00:00` string. 

So, this is not as much of a problem with the SDK, but with the API itself which seems to be replying with invalid datetime strings.

**Comment by renato-gomes** [comment]
Hi,
Please check if Version: 1.1.2RC1 solves your problem.
